Update CMakeLists.txt to address [-Werror,-Winconsistent-missing-override]
This should suppress an error arising from:

    In file included from ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.cpp:2:
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.h:102:21: error: 'process_config' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            virtual int process_config(ACE_Message_Block* mb);
                        ^
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconGadget.h:82:21: note: overridden virtual function is here
            virtual int process_config(ACE_Message_Block* mb);
                        ^
    In file included from ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.cpp:2:
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.h:103:21: error: 'process' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            virtual int process(Gadgetron::GadgetContainerMessage< IsmrmrdReconData >* m1);
                        ^
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconGadget.h:83:21: note: overridden virtual function is here
            virtual int process(Gadgetron::GadgetContainerMessage< IsmrmrdReconData >* m1);