More generic search, and addition of compiler directives for Clang (#1105)
* Simplify search for Clang

Making search for Clang compiler more generic. Also matches what is done lower down in the same CMakeLists.txt file.

* Update CMakeLists.txt to address [-Werror,-Winconsistent-missing-override]

This should suppress an error arising from:

    In file included from ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.cpp:2:
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.h:102:21: error: 'process_config' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            virtual int process_config(ACE_Message_Block* mb);
                        ^
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconGadget.h:82:21: note: overridden virtual function is here
            virtual int process_config(ACE_Message_Block* mb);
                        ^
    In file included from ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.cpp:2:
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.h:103:21: error: 'process' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            virtual int process(Gadgetron::GadgetContainerMessage< IsmrmrdReconData >* m1);
                        ^
    ~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericReconGadget.h:83:21: note: overridden virtual function is here
            virtual int process(Gadgetron::GadgetContainerMessage< IsmrmrdReconData >* m1);

* Update CMakeLists.txt to address [-Werror,-Warray-bounds]

Should generally address errors/warnings like:

    In file included from ~/my_root/src/gadgetron/toolboxes/core/cpu/image/hoNDImage.h:501:
    ~/my_root/src/gadgetron/toolboxes/core/cpu/image/hoNDImage.hxx:1642:17: error: array index 2 is past the end of the array (which contains 2 elements) [-Werror,-Warray-bounds]
                  + this->origin_[2]);
                    ^             ~

* Update CMakeLists.txt to address [-Werror,-Wswitch]

Addresses:

    ~/my_root/src/gadgetron/gadgets/mri_core/CompressedFloatBuffer.cpp:9:13: error: enumeration value 'Scalar' not handled in switch [-Werror,-Wswitch]
        switch (instructionSet)
                ^

* Update CMakeLists.txt to address [-Werror,-Wdynamic-class-memaccess]

To address:
   
    ~/my_root/src/gadgetron/toolboxes/core/cpu/hoNDArray.hxx:830:72: error: source of this 'memcpy' call is a pointer to dynamic class 'hoMRImage<float, 3>'; vtable pointer will be copied [-Werror,-Wdynamic-class-memaccess]
                memcpy(buf + sizeof(size_t) + sizeof(size_t) * NDim, this->data_, sizeof(T) * elements_);
                ~~~~~~                                                     ^

* Update CMakeLists.txt to address [-Werror,-Wundefined-var-template]

In file included from ~/my_root/src/gadgetron/toolboxes/fatwater/graph_cut.cpp:6:
~/my_root/src/gadgetron/toolboxes/fatwater/ImageGraph.h:124:47: error: instantiation of variable 'Gadgetron::ImageGraph<2>::index_to_offset' required here, but no definition is available [-Werror,-Wundefined-var-template]
                    vector_td<int,D> offset = index_to_offset[index_offset];
                                              ^

* Update CMakeLists.txt to address [-Werror,-Wparentheses]

~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericImageReconGadget.cpp:1212:21: error: using the result of an assignment as a condition without parentheses [-Werror,-Wparentheses]
        else if (m2 = AsContainerMessage<Image3DBufferType>(mb))
                 ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericImageReconGadget.cpp:1208:16: note: place parentheses around the assignment to silence this warning
        if (m1 = AsContainerMessage<Image2DBufferType>(mb))
               ^
            (                                             )
~/my_root/src/gadgetron/gadgets/mri_core/generic_recon_gadgets/GenericImageReconGadget.cpp:1208:16: note: use '==' to turn this assignment into an equality comparison
        if (m1 = AsContainerMessage<Image2DBufferType>(mb))
               ^
               ==